name: Deploy Web App
on: 
  push:
    branches:
      - master

env:
  APP_NAME: book-exchange-mock
  RESOURE_GROUP: book-exchange

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout GitHub Action
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: azure/docker-login@v1
      with:
        login-server: mycontainer.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}  

    - name: Restart Web App
      run: |
        az webapp restart --name ${APP_NAME} --resource-group ${RESOURE_GROUP}

    - name: Azure logout
      run: |
        az logout
